import { defineConfig, devices } from "@playwright/test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const repositoryRoot = resolve(__dirname, "..");
try {
  for (const line of readFileSync(resolve(__dirname, ".env"), "utf8").split(/\r?\n/)) {
    const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (!match || process.env[match[1]] !== undefined) continue;
    process.env[match[1]] = match[2].replace(/^(?:"(.*)"|'(.*)')$/, "$1$2");
  }
} catch (error) {
  if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
}
const target = process.env.PLAYWRIGHT_TARGET ?? "local-mock";
const liveBackend = target === "local-live";
const embeddedPreview = target === "embedded-local";
const physicalTarget = target === "pico" || liveBackend;

function normalizeDeviceOrigin(value: string) {
  const candidate = /^https?:\/\//i.test(value) ? value : `http://${value}`;
  const url = new URL(candidate);
  if (url.protocol !== "http:" || url.username || url.password ||
      (url.pathname !== "/" && url.pathname !== "") || url.search || url.hash) {
    throw new Error(`Invalid PICO_CLOCK_API_URL: ${value}`);
  }
  return url.origin;
}

const configuredDevice = process.env.PICO_CLOCK_API_URL ??
  (process.env.PICO_HOSTNAME
    ? [process.env.PICO_HOSTNAME, process.env.PICO_DOMAIN_NAME]
      .filter(Boolean).join(".")
    : "");
if ((target === "pico" || liveBackend) && !configuredDevice) {
  throw new Error(
    "Physical tests require web/.env generated by make flash, or an explicit PICO_CLOCK_API_URL.",
  );
}
const picoOrigin = configuredDevice
  ? normalizeDeviceOrigin(configuredDevice)
  : "http://127.0.0.1";
const externalBaseUrl = process.env.PLAYWRIGHT_BASE_URL ??
  (target === "pico" ? picoOrigin : undefined);
if (!process.env.PICO_CLOCK_TEST_PORT) {
  process.env.PICO_CLOCK_TEST_PORT = String(
    35_000 + (process.pid % 10_000) * 2,
  );
}
if (!process.env.PICO_CLOCK_TEST_RUN_ID) {
  process.env.PICO_CLOCK_TEST_RUN_ID =
    `${Date.now()}-${process.env.PICO_CLOCK_TEST_PORT}`;
}
const testPort = Number(process.env.PICO_CLOCK_TEST_PORT);
if (!Number.isInteger(testPort) || testPort < 1024 || testPort > 65_534) {
  throw new Error(`Invalid PICO_CLOCK_TEST_PORT: ${testPort}`);
}
const webPort = testPort;
const mockPort = testPort + 1;
const buildDirectory = liveBackend ? ".next-playwright-live" : ".next-playwright";
const baseURL = externalBaseUrl ?? `http://127.0.0.1:${webPort}`;

export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: false,
  workers: 1,
  // A physical Wi-Fi device can briefly disappear during DHCP renewal or
  // radio recovery. Preserve the first trace and retry once; deterministic
  // local suites still fail immediately.
  retries: physicalTarget ? 1 : 0,
  timeout: 30_000,
  expect: { timeout: 8_000 },
  outputDir: resolve(
    __dirname, "test-results", `${target}-${process.env.PICO_CLOCK_TEST_RUN_ID}`,
  ),
  reporter: process.env.CI ? [["line"], ["html", { open: "never" }]] : "list",
  use: {
    baseURL,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },
  webServer: externalBaseUrl ? undefined : {
    command: embeddedPreview
      ? `PICO_CLOCK_EMBEDDED_PORT=${webPort} PICO_CLOCK_MOCK_PORT=${mockPort} node scripts/preview-embedded-web.mjs`
      : `${liveBackend ? `PICO_CLOCK_API_URL=${picoOrigin} ` : ""}PICO_CLOCK_DEV_PORT=${webPort} PICO_CLOCK_MOCK_PORT=${mockPort} PICO_CLOCK_NEXT_DIST_DIR=${buildDirectory} node scripts/dev.mjs`,
    cwd: repositoryRoot,
    url: baseURL,
    reuseExistingServer: false,
    timeout: 120_000,
    gracefulShutdown: { signal: "SIGTERM", timeout: 5_000 },
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
